---
- name: Debian | Include apt codename generation tasks
  ansible.builtin.include_tasks:
    file: apt-codename.yml

- name: Debian | Apt Dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ tailscale_apt_dependencies }}"
    cache_valid_time: 3600
    state: present

- name: Debian | Add Tailscale Repository
  become: true
  ansible.builtin.deb822_repository:
    name: tailscale
    types: deb
    uris: https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ tailscale_debian_distro[ansible_distribution | lower] }}
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: "{{ tailscale_apt_signkey }}"
    state: present

- name: Debian | Remove Legacy Tailscale Deb
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ tailscale_apt_deb }}"
    state: absent
    codename: "{{ apt_codename }}"

- name: Debian | Remove Tailscale Signing Key from legacy keyrings path
  become: true
  ansible.builtin.file:
    path: "{{ tailscale_apt_keyring_path }}"
    state: absent

- name: Debian | Install Tailscale
  become: true
  ansible.builtin.apt:
    name: "{{ tailscale_package }} iproute2"
    install_recommends: false
    update_cache: true
    state: "{{ state }}"
