---
provisioner:
  playbooks:
    prepare: ../role-machine-default/prepare.yml

scenario:
  name: role-machine-args
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
