---
- name: Fedora | Prepare Systemd
  ansible.builtin.import_tasks: ./systemd.yml

- name: Fedora | DNF Plugins
  become: true
  ansible.builtin.dnf:
    name: "{{ tailscale_dnf_plugins }}"
    update_cache: true
    state: present

- name: Fedora | DNF Dependencies
  become: true
  ansible.builtin.dnf:
    name: "{{ tailscale_dnf_dependencies }}"
    state: present

- name: Fedora (Version <=40) | Add DNF Repo
  become: true
  ansible.builtin.command: dnf config-manager --add-repo {{ tailscale_dnf_repos[ansible_distribution] }}
  args:
    creates: /etc/yum.repos.d/tailscale.repo
  when: ansible_facts['distribution_version'] | int <= 40

- name: Fedora (Version >= 41) | Add DNF Repo
  become: true
  ansible.builtin.command: dnf config-manager addrepo --from-repofile={{ tailscale_dnf_repos[ansible_distribution] }}
  args:
    creates: /etc/yum.repos.d/tailscale.repo
  when: ansible_facts['distribution_version'] | int >= 41

- name: Fedora | Install Tailscale
  become: true
  ansible.builtin.dnf:
    name: "{{ tailscale_package }}"
    update_cache: true
    state: '{{ state }}'
